global:
  slack_api_url: "https://hooks.slack.com/services/your/slack/api/token"

route:
  receiver: "slack-notifications"

receivers:
  - name: "slack-notifications"
    slack_configs:
      - channel: "#alerts"
        send_resolved: true
